# Generated by Django 2.0.7 on 2020-10-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='products',
        ),
    ]
